baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://lordbonzi.pro" # the base hostname & protocol for your site.

logo: "https://f4.bcbits.com/img/a1818480888_16.jpg"

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
author: LordBonzi
title: LordBonzi
header: Stuff and Things

monzo_me: lordbonzi

# for welcome page
# to replace image go to index.html
email:
  address: "bonzi@lordbonzi.pro"
  text: "bonzi (at) lordbonzi.pro"

# disqus comment
disqus:
    shortname: "" #your disqus comment short name

# google analytics
google:
    tracking-id: "" #your tracking id here

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

include: [".well-known"]
